version: '2'
services:
            
   country-a-es:
       build: 
           context: ./
           dockerfile: ./country-a-es/Dockerfile
       volumes:
         - ./country-a-es:/home
         - ./country-a-es/openncp-configuration:/opt/openncp-configuration
       depends_on: 
         - mysql-filler
       command: bash -c "sleep 40 && /usr/local/tomcat/bin/catalina.sh run"
       networks:
         openncp-net:
            ipv4_address: 10.5.0.5

   country-b-it:
       build: 
           context: ./
           dockerfile: ./country-b-it/Dockerfile
       volumes:
         - ./country-b-it:/home
         - ./country-b-it/openncp-configuration:/opt/openncp-configuration
       depends_on: 
         - mysql-filler
       command: bash -c "sleep 40 && /usr/local/tomcat/bin/catalina.sh run"
       networks:
         openncp-net:
            ipv4_address: 10.5.0.6
           
   portal: 
       build: 
           context: ./
           dockerfile: ./lportal/Dockerfile
       volumes:
         - ./lportal:/home
         - ./lportal/openncp-configuration:/opt/openncp-configuration
       depends_on: 
         - mysql-filler
       command: bash -c  "sleep 55 && /usr/local/liferay-portal/tomcat/bin/catalina.sh run"
       ports:
         - 127.0.0.1:8081:8081
       networks:
         openncp-net:
            ipv4_address: 10.5.0.8            
            
   mysql-it: 
       image: mysql:5.7 
       volumes: 
         - ./mysql-db/db-it:/var/lib/mysql
         - ./mysql-db/custom.cnf:/etc/mysql/conf.d/custom.cnf
       ports:
         - 3306:3306
       environment:
         - MYSQL_ROOT_PASSWORD=konfido
         - MYSQL_USER=root
         - MYSQL_DATABASE=openncp_properties
       networks:
         openncp-net:
            ipv4_address: 10.5.0.7
            
   mysql-es: 
       image: mysql:5.7 
       volumes: 
         - ./mysql-db/db-es:/var/lib/mysql
         - ./mysql-db/custom.cnf:/etc/mysql/conf.d/custom.cnf
       ports:
         - 3307:3306
       environment:
         - MYSQL_ROOT_PASSWORD=konfido
         - MYSQL_USER=root
         - MYSQL_DATABASE=openncp_properties
       networks:
         openncp-net:
            ipv4_address: 10.5.0.9
             
   mysql-filler:
       build: 
           context: ./mysql-db/mysql-filler
           dockerfile: ./Dockerfile
       volumes:
         - ./mysql-db/mysql-filler:/home

       depends_on: 
         - mysql-it
         - mysql-es
       command: bash -c "/home/startup.sh"
       networks:
         openncp-net:
            ipv4_address: 10.5.0.4
                   
         
networks:
     openncp-net:
       driver: bridge
       ipam:
         driver: default
         config:
         -
           subnet: 10.5.0.0/24     
