CREATE DATABASE IF NOT EXISTS hcer;
CREATE DATABASE IF NOT EXISTS eadc;
CREATE DATABASE IF NOT EXISTS openatna;
CREATE DATABASE IF NOT EXISTS lportal;
CREATE DATABASE IF NOT EXISTS openncp_logs;
CREATE DATABASE IF NOT EXISTS tsam;

USE openncp_properties;


UPDATE property SET is_smp = false;
