debug: false
ehealth:
  termserver:
    base-url: https://webgate.training.ec.europa.eu/ehealth-term-server
    username: translator@it
    password: 123456
logging:
  level:
     org.hibernate: ERROR
     org.springframework.web.client: DEBUG
openncp:
  ltrdb:
    host: 127.0.0.1
    port: 3306
    username: root
    password: konfido
    database-name: tsam
  tsam-sync:
    proxy:
      use: false
      host: my.proxy.host
      port: 9999
      use-authentication: true
      username: proxy_user
      password: proxy_password
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/tsam
    username: root
    password: konfido
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: mysql
 